module Deb558
  module Config
      BLOCK_SIZE = 200
      RECORD_TYPE_POSITION = 41
      RECORD_ID_POSITION = 0
      PREVIOUS_BALANCE_RECORD_TYPE = 0
      JOURNAL_ENTRY_RECORD_TYPE = 1
      CURRENT_BALANCE_RECORD_TYPE = 2
      HEADER_RECORD_ID = 0
      DETAIL_RECORD_ID = 1
      TRAILER_RECORD_ID = 9
  end
end
